<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Docker</AssemblyName>
    <RootNamespace>Inedo.Extensions.Docker</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Inedo.SDK" Version="4.0.0" ExcludeAssets="runtime" />
    <PackageReference Include="Inedo.ProGet" Version="2.2.2-ci.1" />
  </ItemGroup>
</Project>